[package]
name = "rust_word_counter"
version = "0.1.0"
edition = "2024"
description = "Measures word frequency in a file."

[dependencies]
clap = { version = "4.5", features = ["derive"] }

[[bin]]
name = "rust_word_counter"
path = "main.rs"
